# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
