# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='available_dates',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='disable_dates',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='modified_date',
        ),
    ]
