# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20170815_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
