# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 11:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('introduce', models.TextField(blank=True, max_length=1000, null=True)),
                ('space_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('guest_access', models.TextField(blank=True, max_length=1000, null=True)),
                ('price_per_day', models.PositiveIntegerField()),
                ('extra_people_fee', models.PositiveIntegerField()),
                ('cleaning_fee', models.PositiveIntegerField()),
                ('weekly_discount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('accommodates', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('beds', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('House', '집전체'), ('Individual', '개인실'), ('Shared_Room', '다인실')], default='House', max_length=20)),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('amenities', models.ManyToManyField(related_name='amenities_manager', to='house.Amenities')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='HouseImage')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='house.House')),
            ],
        ),
    ]
