# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='house.Price'),
        ),
        migrations.AddField(
            model_name='house',
            name='space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='house.Space'),
        ),
    ]
