# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='amenities',
            field=models.CharField(default=12314, max_length=200),
            preserve_default=False,
        ),
    ]
