# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20170801_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='amenities',
        ),
    ]
