# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20170720_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='room_type',
            field=models.CharField(choices=[('House', '집전체'), ('Individual', '개인실'), ('Shared_Room', '다인실')], default='House', max_length=3),
        ),
    ]
