# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_remove_house_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='amenities',
            field=models.ManyToManyField(related_name='amenities', to='house.Amenities'),
        ),
    ]
