# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20170801_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amenities',
            field=models.ManyToManyField(related_name='amenities_manager', to='house.Amenities'),
        ),
    ]
