# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20170720_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='guest_access',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='introduce',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='room_type',
            field=models.CharField(choices=[('House', '집전체'), ('Individual', '개인실'), ('Shared_Room', '다인실')], default='House', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='space_info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
