# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20170722_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='weekly_discount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
