# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20170802_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.FloatField(default=23.234234, verbose_name='위도'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.FloatField(default=12.234553, verbose_name='경도'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='guest_access',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='introduce',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='space_info',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.TextField(max_length=300),
        ),
    ]
