# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20170802_2309'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='images',
            order_with_respect_to='house',
        ),
    ]
