# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_auto_20170803_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
