# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0009_auto_20170803_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='reservation_user_set',
            field=models.ManyToManyField(blank=True, null=True, related_name='reservation_user_set', through='reservations.Reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
