# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_house_reservation_user_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='reservation_user_set',
            field=models.ManyToManyField(blank=True, related_name='reservation_user_set', through='reservations.Reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
