# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
        ('house', '0010_auto_20170807_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='guest',
            field=models.ManyToManyField(related_name='reservations_to', through='reservations.Reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
