# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_house_guest'),
    ]

    operations = [
    ]
