# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0002_auto_20170809_1525'),
        ('house', '0011_auto_20170809_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='reservation_user_set',
        ),
        migrations.AddField(
            model_name='house',
            name='reservations',
            field=models.ManyToManyField(blank=True, related_name='reservations_to', through='reservations.Reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
