# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlist', '0001_initial'),
        ('house', '0011_house_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_liker',
            field=models.ManyToManyField(related_name='get_wishlist', through='wishlist.Wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
