# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0004_auto_20170809_1536'),
        ('house', '0012_auto_20170809_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='reservations',
        ),
        migrations.AddField(
            model_name='house',
            name='guest_user',
            field=models.ManyToManyField(blank=True, related_name='reserved_house', through='reservations.Reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
