# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0012_house_house_liker'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_review',
            field=models.ManyToManyField(related_name='get_review', through='review.Review', to=settings.AUTH_USER_MODEL),
        ),
    ]
