# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_house_house_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisableDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='disable_days',
            field=models.ManyToManyField(related_name='disabled_day_manager', to='house.DisableDay'),
        ),
    ]
