# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_holidays'),
        ('house', '0013_house_house_review'),
    ]

    operations = [
    ]
