# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_auto_20170817_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabledday',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
