# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_auto_20170817_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disable_days',
            new_name='DisableDay',
        ),
    ]
