# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('MALE', '남자'), ('FEMALE', '여자'), ('OTHER', '기타')], default='MALE', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='introduce',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='living_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='preference_currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='preference_language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
