# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170730_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('MALE', '남자'), ('FEMALE', '여자'), ('OTHER', '기타')], default='OTHER', max_length=10),
        ),
    ]
