# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170731_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='identifier',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
