# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170731_2306'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
