# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20170731_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='identifier',
            field=models.CharField(default=123, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
