# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20170731_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
