# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import member.models.users


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20170731_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='identifier',
            field=models.CharField(default=member.models.users.f, max_length=40, unique=True),
        ),
    ]
