# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20170801_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('django', 'Django'), ('facebook', 'Facebook')], default='Django', max_length=20),
            preserve_default=False,
        ),
    ]
