# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:27
from __future__ import unicode_literals

from django.db import migrations
import member.models.users


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20170801_0002'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', member.models.users.NewUserManager()),
            ],
        ),
    ]
