# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import member.models.users


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_house_guest'),
        ('wishlist', '0001_initial'),
        ('member', '0007_auto_20170801_0002'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', member.models.users.NewUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='identifier',
        ),
        migrations.AddField(
            model_name='myuser',
            name='like_houses',
            field=models.ManyToManyField(related_name='wishlist_info', through='wishlist.Wishlist', to='house.House'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('django', 'Django'), ('facebook', 'Facebook')], default='django', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
