# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_house_guest'),
        ('wishlist', '0001_initial'),
        ('member', '0007_auto_20170801_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='like_houses',
            field=models.ManyToManyField(related_name='my_wishlist', through='wishlist.Wishlist', to='house.House'),
        ),
    ]
