# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_myuser_like_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='like_houses',
            field=models.ManyToManyField(related_name='wishlist_info', through='wishlist.Wishlist', to='house.House'),
        ),
    ]
