# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_myuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('django', 'Django'), ('facebook', 'Facebook')], default='django', max_length=20),
        ),
    ]
