# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20170815_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
