# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import member.models.users


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20170813_1717'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', member.models.users.NewUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
