# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='likers',
            new_name='liker',
        ),
    ]
